### ISSUE TITLE
Superuser cannot see all accounts

### ISSUE THREAD

**Issue by rmescandon** [CanonicalLtd/serial-vault#101]
The superuser should be able to see all accounts, but currently can only see the ones assigned to the current user. This also happens with models: current user cannot see models whose brand is not an account related to him

**Comment by slimjim777** [comment]
This applies to other things as well e.g. models and logs. We may just need to amend the queries:


	select m.id, brand_id, m.name, keypair_id, api_key, k.authority_id, k.key_id, k.active, user_keypair_id, ku.authority_id, ku.key_id, ku.active, ku.assertion
	from model m
	inner join keypair k on k.id = m.keypair_id
	inner join keypair ku on ku.id = m.user_keypair_id
	inner join account acc on acc.authority_id=m.brand_id
	inner join useraccountlink ua on ua.account_id=acc.id
	inner join userinfo u on ua.user_id=u.id
	where u.username=$1 and **(u.userrole >= $2 or u.userrole=300)**
	order by name
