### ISSUE TITLE
Wishlist: modify snap apps names

### ISSUE THREAD

**Issue by rmescandon** [CanonicalLtd/serial-vault#142]
rename:
serial-vault to 'service'
serial-vault-admin to 'admin'

Service won't be invoked directly as it is a service, so that one is less important, but in the second case, we reduce the call from
`serial-vault.serial-vault-admin `
to a shorter and less redundante 
`serial-vault.admin`

**Comment by pvanloo** [comment]
I can take a shot at this

**Comment by rmescandon** [comment]
@pvanloo great!. Go for it if you want
