### ISSUE TITLE
dependencies.tsv needs to be updated

### ISSUE THREAD

**Issue by ejfinneran** [CanonicalLtd/serial-vault#190]
Looks like a logging dependency was added recently via 86d7129c but isn't included in `dependencies.tsv` so trying to run anything results in:

```
service/log/log.go:26:2: cannot find package "github.com/op/go-logging" in any of:
	/go/src/github.com/CanonicalLtd/serial-vault/vendor/github.com/op/go-logging (vendor tree)
	/usr/local/go/src/github.com/op/go-logging (from $GOROOT)
	/go/src/github.com/op/go-logging (from $GOPATH)
```

**Comment by slimjim777** [comment]
We've actually switched to using govendor instead of the godeps, so we're planning to remove dependencies.tsv. You can update the dependencies now using:

./get-deps.sh

**Comment by slimjim777** [comment]
The file has now been removed
