### ISSUE TITLE
Can't register key from UX

### ISSUE THREAD

**Issue by knitzsche** [CanonicalLtd/serial-vault#234]
In partners, customer failed to register a key using Signing Keys > Register Signing Key with Store. 

Error: "fetch-keypair: Cannot find the signing key" [1]

I duplicated the same error on staging. 

The key was previously generated from the SV UX. (Signing Keys page > gear button, which appears to have succeeded. 

In the register form, the key is selected from the drop-down and the credentials for the brand account are entered, including email, password and OTP (which is the single-factor one-time-pword for the Ubuntu SSO account). 

[1] https://github.com/CanonicalLtd/serial-vault/blob/6bdeb46d617701fd87201aff9f2759a0881dec77/service/store/actions.go#L50

**Comment by glower** [comment]
Here is the fix: https://github.com/CanonicalLtd/serial-vault/pull/238

**Comment by glower** [comment]
Fixed with Version: 2.4-10
@knitzsche can you please verify it on staging, the new version is deployed there

**Comment by knitzsche** [comment]
Seems to have worked on staging on 26 June 2019. Thanks.
