### ISSUE TITLE
wishlist: service/utils.go methods should be in their respective files

### ISSUE THREAD

**Issue by rmescandon** [CanonicalLtd/serial-vault#87]
_Wishlist:_

There are a bunch of formatXXX methods in service/utils.go that are specific of their section. For instance formatModelsResponse() should be included in handlers_models.go.
An even better solution should be having a common method to format the responses using interface{} as generic type and pointers for struct member reference (though maybe this second option is a bit dirty to read)

**Comment by slimjim777** [comment]
This has now been done with the refactor of the handlers.
