### ISSUE TITLE
Somebody review Zh labels

### ISSUE THREAD

**Issue by rmescandon** [CanonicalLtd/serial-vault#88]
Zh labels in webapp/js/components/messages.js must be reviewed and modified if needed by somebody knowing the language. They have been filled using an automatic translator

**Comment by slimjim777** [comment]
Now that we are focusing on a central hosted service, this is probably less important.

**Comment by slimjim777** [comment]
The factory-serial-vault is now just the Signing service that is synced with the cloud service, so there is no UI that needs translation.
